### ISSUE TITLE
ServerServiceGrpc 找不到

### ISSUE THREAD

**Issue by houko** [jzyong/mmo-server#5]
缺少proto文件

**Comment by jzyong** [comment]
运行maven插件生成一下

**Comment by houko** [comment]
> 运行maven插件生成一下

不好意思，能说的详细点吗？

**Comment by houko** [comment]
![image](https://user-images.githubusercontent.com/12625278/103865259-4473e900-5107-11eb-86ee-09548de507f4.png)
生成的文件中没有ServerServiceGrpc和AccountServiceGrpc

**Comment by jzyong** [comment]
mmo-message package能成功吗 profile选择jzy

**Comment by houko** [comment]
> mmo-message package能成功吗 profile选择jzy

![image](https://user-images.githubusercontent.com/12625278/103868074-bc441280-510b-11eb-912f-00a9f6664c8f.png)
